// STATE VARIABLES

// alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// MARK:- BUSINESS
export const REGISTER_SUCCESS_BUSINESS = "REGISTER_SUCCESS_BUSINESS";
export const REGISTER_FAILED_BUSINESS = "REGISTER_FAILED_BUSINESS";
export const USERLOADED_SUCCESS_BUSINESS = "USERLOADED_SUCCESS_BUSINESS";
export const USERLOADED_FAILED_BUSINESS = "USERLOADED_FAILED_BUSINESS";
export const LOGIN_SUCCESS_BUSINESS = "LOGIN_SUCCESS_BUSINESS";
export const LOGIN_FAILED_BUSINESS = "LOGIN_FAILED_BUSINESS";
export const LOGOUT_SUCCESS_BUSINESS = "LOGOUT_SUCCESS_BUSINESS";
// MARK:- USER
export const REGISTER_SUCCESS_USER = "REGISTER_SUCCESS_USER";
export const REGISTER_FAILED_USER = "REGISTER_FAILED_USER";
export const USERLOADED_SUCCESS_USER = "USERLOADED_SUCCESS_USER";
export const USERLOADED_FAILED_USER = "USERLOADED_FAILED_USER";
export const LOGIN_SUCCESS_USER = "LOGIN_SUCCESS_USER";
export const LOGIN_FAILED_USER = "LOGIN_FAILED_USER";
export const LOGOUT_SUCCESS_USER = "LOGOUT_SUCCESS_USER";
// MARK:- ADMIN
export const REGISTER_SUCCESS_ADMIN = "REGISTER_SUCCESS_ADMIN";
export const REGISTER_FAILED_ADMIN = "REGISTER_FAILED_ADMIN";
export const USERLOADED_SUCCESS_ADMIN = "LOADED_SUCCESS_ADMIN";
export const USERLOADED_FAILED_ADMIN = "USERLOADED_FAILED_ADMIN";
export const LOGIN_SUCCESS_ADMIN = "LOGIN_SUCCESS_ADMIN";
export const LOGIN_FAILED_ADMIN = "LOGIN_FAILED_ADMIN";
export const LOGOUT_SUCCESS_ADMIN = "LOGOUT_SUCCESS_ADMIN";
// MARK:- ITEM
// business
export const CREATE_ITEM_SUCCESS_BUSINESS = "CREATE_ITEM_SUCCESS_BUSINESS";
export const CREATE_ITEM_FAILED_BUSINESS = "CREATE_ITEM_FAILED_BUSINESS";
export const GET_ALL_MY_ITEMS_SUCCESS_BUSINESS = "GET_ALL_MY_ITEMS_BUSINESS";
export const GET_ALL_MY_ITEMS_FAILED_BUSINESS = "GET_ALL_MY_ITEMS_BUSINESS";
export const GET_ONE_ITEM_SUCCESS_BUSINESS = "GET_ONE_ITEM_SUCCESS_BUSINESS";
export const GET_ONE_ITEM_FAILED_BUSINESS = "GET_ONE_ITEM_FAILED_BUSINESS";
export const GET_RENTEE_SUCCESS_BUSINESS = "GET_RENTEE_SUCCESS_BUSINESS";
export const GET_RENTEE_FAILED_BUSINESS = "GET_RENTEE_FAILED_BUSINESS";
export const SET_RENTEE_SUCCESS_BUSINESS = "SET_RENTEE_SUCCESS_BUSINESS";
export const SET_RENTEE_FAILED_BUSINESS = "SET_RENTEE_FAILED_BUSINESS";
export const GET_TIMES_RENTED_SUCCESS_BUSINESS = "GET_TIMES_RENTED_SUCCESS_BUSINESS";
export const GET_TIMES_RENTED_FAILED_BUSINESS = "GET_TIMES_RENTED_FAILED_BUSINESS";
export const SET_LOCATION_SUCCESS_BUSINESS = "SET_LOCATION_SUCCESS_BUSINESS";
export const SET_LOCATION_FAILED_BUSINESS = "SET_LOCATION_FAILED_BUSINESS";
// actions
export const GET_ITEMS_FOR_RENT_SUCCESS_BUSINESS = "GET_ITEMS_FOR_RENT_SUCCESS_BUSINESS";
export const GET_ITEMS_FOR_RENT_FAILED_BUSINESS = "GET_ITEMS_FOR_RENT_FAILED_BUSINESS";
export const GET_ITEMS_RENTED_OUT_SUCCESS_BUSINESS = "GET_ITEMS_RENTED_OUT_SUCCESS_BUSINESS";
export const GET_ITEMS_RENTED_OUT_FAILED_BUSINESS = "GET_ITEMS_RENTED_OUT_FAILED_BUSINESS";
// user
export const GET_ALL_ITEMS_SUCCESS_USER = "GET_ALL_ITEMS_SUCCESS_USER";
export const GET_ALL_ITEMS_FAILED_USER = "GET_ALL_ITEMS_FAILED_USER";
export const GET_ONE_ITEM_SUCCESS_USER = "GET_ONE_ITEM_FAILED_USER";
export const GET_ONE_ITEM_FAILED_USER = "GET_ONE_ITEM_FAILED_USER";

// user actions
export const GET_FAVOURITES_SUCCESS_USER = "GET_FAVOURITES_SUCCESS_USER";
export const GET_FAVOURTIES_FAILED_USER = "GET_FAVOURITES_FAILED_USER";
export const ADD_FAVOURITES_SUCCESS_USER = "ADD_FAVOURITES_SUCCESS_USER";
export const ADD_FAVOURITES_FAILED_USER = "ADD_FAVOURITES_FAILED_USER";
export const REMOVE_FAVOURITES_SUCCESS_USER = "REMOVE_FAVOURITES_SUCCESS_USER";
export const REMOVE_FAVOURITES_FAILED_USER = "REMOVE_FAVOURITES_FAILED_USER";
export const GET_RESERVED_ITEMS_SUCCESS_USER = "GET_RESERVED_ITEMS_SUCCESS_USER";
export const GET_RESERVED_ITEMS_FAILED_USER = "GET_RESERVED_ITEMS_FAILED_USER";
export const SET_RESERVED_ITEMS_SUCCESS_USER = "SET_RESERVED_ITEMS_SUCCESS_USER";
export const SET_RESERVED_ITEMS_FAILED_USER = "SET_RESERVED_ITEMS_FAILED_USER";
export const REMOVE_RESERVED_ITEMS_SUCCESS_USER = "REMOVE_RESERVED_ITEMS_SUCCESS_USER";
export const REMOVE_RESERVED_ITEMS_FAILED_USER = "REMOVE_RESERVED_ITEMS_FAILED_USER";
export const GET_FOLLOWERS_SUCCESS_USER = "GET_FOLLOWERS_SUCCESS_USER";
export const GET_FOLLOWERS_FAILED_USER = "GET_FOLLOWERS_FAILED_USER";
export const GET_FOLLOWING_SUCCESS_USER = "GET_FOLLOWING_SUCCESS_USER";
export const GET_FOLLOWING_FAILED_USER = "GET_FOLLOWING_FAILED_USER";
export const FOLLOW_SUCCESS_USER = "FOLLOW_SUCCESS_USER";
export const FOLLOW_FAILED_USER = "FOLLOW_FAILED_USER";
export const UNFOLLOW_SUCCESS_USER = "UNFOLLOW_SUCCESS_USER";
export const UNFOLLOW_FAILED_USER = "UNFOLLOW_FAILED_USER";
export const SET_PUBLIC_PROFILE_SUCCESS_USER = "SET_PUBLIC_PROFILE_SUCCESS_USER";
export const SET_PUBLIC_PROFILE_FAILED_USER = "SET_PUBLIC_PROFILE_FAILED_USER";
