// STATE VARIABLES

// alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// MARK:- BUSINESS
export const REGISTER_SUCCESS_BUSINESS = "REGISTER_SUCCESS_BUSINESS";
export const REGISTER_FAILED_BUSINESS = "REGISTER_FAILED_BUSINESS";
export const USERLOADED_SUCCESS_BUSINESS = "USERLOADED_SUCCESS_BUSINESS";
export const USERLOADED_FAILED_BUSINESS = "USERLOADED_FAILED_BUSINESS";
export const LOGIN_SUCCESS_BUSINESS = "LOGIN_SUCCESS_BUSINESS";
export const LOGIN_FAILED_BUSINESS = "LOGIN_FAILED_BUSINESS";
export const LOGOUT_SUCCESS_BUSINESS = "LOGOUT_SUCCESS_BUSINESS";
// MARK:- USER
export const REGISTER_SUCCESS_USER = "REGISTER_SUCCESS_USER";
export const REGISTER_FAILED_USER = "REGISTER_FAILED_USER";
export const USERLOADED_SUCCESS_USER = "USERLOADED_SUCCESS_USER";
export const USERLOADED_FAILED_USER = "USERLOADED_FAILED_USER";
export const LOGIN_SUCCESS_USER = "LOGIN_SUCCESS_USER";
export const LOGIN_FAILED_USER = "LOGIN_FAILED_USER";
export const LOGOUT_SUCCESS_USER = "LOGOUT_SUCCESS_USER";
// MARK:- ADMIN
export const REGISTER_SUCCESS_ADMIN = "REGISTER_SUCCESS_ADMIN";
export const REGISTER_FAILED_ADMIN = "REGISTER_FAILED_ADMIN";
export const USERLOADED_SUCCESS_ADMIN = "LOADED_SUCCESS_ADMIN";
export const USERLOADED_FAILED_ADMIN = "USERLOADED_FAILED_ADMIN";
export const LOGIN_SUCCESS_ADMIN = "LOGIN_SUCCESS_ADMIN";
export const LOGIN_FAILED_ADMIN = "LOGIN_FAILED_ADMIN";
export const LOGOUT_SUCCESS_ADMIN = "LOGOUT_SUCCESS_ADMIN";
// MARK:- ITEM
// user
// business
// admin